### ISSUE TITLE
SQLi vulnerabilities.

### ISSUE THREAD

**Issue by 14u9h** [HurryBy/tanzhen#2]
/modules/getInformation/gps.php文件中第26行，在获取gps_longitude和gps_location值后直接使用了SQL语句将获得的两个值写入到数据库中，而这两个参数值通过自己构建POST包是可控的，当然可控的变量也包括"key"的值，并且程序没有做任何过滤，从而导致在gps.php文件处存在SQL注入漏洞，这块可以做做过滤。
最后，祝好。 ; )
```    include_once(dirname(__FILE__,2)."/mySQL/dbconfig.php");
    // 根据timestamp & key写数据
    $conn = new mysqli($db_host.":".$db_port, $db_user, $db_password, $db_name);
    $sql = "UPDATE `tanzhen_information` SET `gpsaddress` = '$gps_location', `gpsjing` = '$gps_longitude', `gpswei` = '$gps_latitude' WHERE `tanzhen_information`.`timestamp` = '$time' AND `tanzhen_information`.`keyvalue` = '$key';";
```

**Comment by HurryBy** [comment]
您好
非常感谢您能够对我写出来的代码做出评论，我目前也只是一个在校的学生，项目是寒假的时候有空突发奇想写的，自己在编程这块也算是刚入门，现在我每周都要返校，拿到电脑的时间并不多，到了暑假我会按照您的建议去改的！
最后还是十分感谢您能提出建议！
